# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package and tsconfig
COPY package.json tsconfig.json ./

# Copy source files
COPY src ./src

# Install dependencies, build, then prune dev dependencies
RUN npm install && \
    npm run build && \
    npm prune --production

# Set environment to production
ENV NODE_ENV=production

# Expose no ports as it runs via stdio

# Default command
CMD ["node","dist/server.js"]
